### ISSUE TITLE
Use github actions for now deployments

### ISSUE THREAD

**Issue by masterwendu** [masterwendu/babybet#17]
when deploy to master -> deploy to beta.babybet.com
when deploy to any other branch then master -> deploy to now dev enviroment to try it out

**Comment by mridhul** [comment]
@masterwendu : I'ld like to pick this up. 👍

**Comment by masterwendu** [comment]
hey @mridhul ,

thanks for your help. It's just you need the permissions for now. So just I can do it :/ I removed the hacktoberfest label, my mistake

**Comment by masterwendu** [comment]
I did it with the now github integration, without github actions
